/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoBreadcrumbsRouteRouteImport } from './routes/demo/breadcrumbs/route'
import { Route as DemoBreadcrumbsIndexRouteImport } from './routes/demo/breadcrumbs/index'
import { Route as DemoBreadcrumbsOrganizationsIndexRouteImport } from './routes/demo/breadcrumbs/organizations/index'
import { Route as DemoBreadcrumbsOrganizationsOrgIdRouteRouteImport } from './routes/demo/breadcrumbs/organizations/$orgId/route'
import { Route as DemoBreadcrumbsOrganizationsOrgIdIndexRouteImport } from './routes/demo/breadcrumbs/organizations/$orgId/index'
import { Route as DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRouteImport } from './routes/demo/breadcrumbs/organizations/$orgId/employees/index'
import { Route as DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRouteImport } from './routes/demo/breadcrumbs/organizations/$orgId/employees/$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBreadcrumbsRouteRoute = DemoBreadcrumbsRouteRouteImport.update({
  id: '/demo/breadcrumbs',
  path: '/demo/breadcrumbs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBreadcrumbsIndexRoute = DemoBreadcrumbsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoBreadcrumbsRouteRoute,
} as any)
const DemoBreadcrumbsOrganizationsIndexRoute =
  DemoBreadcrumbsOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => DemoBreadcrumbsRouteRoute,
  } as any)
const DemoBreadcrumbsOrganizationsOrgIdRouteRoute =
  DemoBreadcrumbsOrganizationsOrgIdRouteRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => DemoBreadcrumbsRouteRoute,
  } as any)
const DemoBreadcrumbsOrganizationsOrgIdIndexRoute =
  DemoBreadcrumbsOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DemoBreadcrumbsOrganizationsOrgIdRouteRoute,
  } as any)
const DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute =
  DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => DemoBreadcrumbsOrganizationsOrgIdRouteRoute,
  } as any)
const DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute =
  DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => DemoBreadcrumbsOrganizationsOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/breadcrumbs': typeof DemoBreadcrumbsRouteRouteWithChildren
  '/demo/breadcrumbs/': typeof DemoBreadcrumbsIndexRoute
  '/demo/breadcrumbs/organizations/$orgId': typeof DemoBreadcrumbsOrganizationsOrgIdRouteRouteWithChildren
  '/demo/breadcrumbs/organizations': typeof DemoBreadcrumbsOrganizationsIndexRoute
  '/demo/breadcrumbs/organizations/$orgId/': typeof DemoBreadcrumbsOrganizationsOrgIdIndexRoute
  '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId': typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute
  '/demo/breadcrumbs/organizations/$orgId/employees': typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/breadcrumbs': typeof DemoBreadcrumbsIndexRoute
  '/demo/breadcrumbs/organizations': typeof DemoBreadcrumbsOrganizationsIndexRoute
  '/demo/breadcrumbs/organizations/$orgId': typeof DemoBreadcrumbsOrganizationsOrgIdIndexRoute
  '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId': typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute
  '/demo/breadcrumbs/organizations/$orgId/employees': typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/breadcrumbs': typeof DemoBreadcrumbsRouteRouteWithChildren
  '/demo/breadcrumbs/': typeof DemoBreadcrumbsIndexRoute
  '/demo/breadcrumbs/organizations/$orgId': typeof DemoBreadcrumbsOrganizationsOrgIdRouteRouteWithChildren
  '/demo/breadcrumbs/organizations/': typeof DemoBreadcrumbsOrganizationsIndexRoute
  '/demo/breadcrumbs/organizations/$orgId/': typeof DemoBreadcrumbsOrganizationsOrgIdIndexRoute
  '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId': typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute
  '/demo/breadcrumbs/organizations/$orgId/employees/': typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/breadcrumbs'
    | '/demo/breadcrumbs/'
    | '/demo/breadcrumbs/organizations/$orgId'
    | '/demo/breadcrumbs/organizations'
    | '/demo/breadcrumbs/organizations/$orgId/'
    | '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId'
    | '/demo/breadcrumbs/organizations/$orgId/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/breadcrumbs'
    | '/demo/breadcrumbs/organizations'
    | '/demo/breadcrumbs/organizations/$orgId'
    | '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId'
    | '/demo/breadcrumbs/organizations/$orgId/employees'
  id:
    | '__root__'
    | '/'
    | '/demo/breadcrumbs'
    | '/demo/breadcrumbs/'
    | '/demo/breadcrumbs/organizations/$orgId'
    | '/demo/breadcrumbs/organizations/'
    | '/demo/breadcrumbs/organizations/$orgId/'
    | '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId'
    | '/demo/breadcrumbs/organizations/$orgId/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoBreadcrumbsRouteRoute: typeof DemoBreadcrumbsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/breadcrumbs': {
      id: '/demo/breadcrumbs'
      path: '/demo/breadcrumbs'
      fullPath: '/demo/breadcrumbs'
      preLoaderRoute: typeof DemoBreadcrumbsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/breadcrumbs/': {
      id: '/demo/breadcrumbs/'
      path: '/'
      fullPath: '/demo/breadcrumbs/'
      preLoaderRoute: typeof DemoBreadcrumbsIndexRouteImport
      parentRoute: typeof DemoBreadcrumbsRouteRoute
    }
    '/demo/breadcrumbs/organizations/': {
      id: '/demo/breadcrumbs/organizations/'
      path: '/organizations'
      fullPath: '/demo/breadcrumbs/organizations'
      preLoaderRoute: typeof DemoBreadcrumbsOrganizationsIndexRouteImport
      parentRoute: typeof DemoBreadcrumbsRouteRoute
    }
    '/demo/breadcrumbs/organizations/$orgId': {
      id: '/demo/breadcrumbs/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/demo/breadcrumbs/organizations/$orgId'
      preLoaderRoute: typeof DemoBreadcrumbsOrganizationsOrgIdRouteRouteImport
      parentRoute: typeof DemoBreadcrumbsRouteRoute
    }
    '/demo/breadcrumbs/organizations/$orgId/': {
      id: '/demo/breadcrumbs/organizations/$orgId/'
      path: '/'
      fullPath: '/demo/breadcrumbs/organizations/$orgId/'
      preLoaderRoute: typeof DemoBreadcrumbsOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof DemoBreadcrumbsOrganizationsOrgIdRouteRoute
    }
    '/demo/breadcrumbs/organizations/$orgId/employees/': {
      id: '/demo/breadcrumbs/organizations/$orgId/employees/'
      path: '/employees'
      fullPath: '/demo/breadcrumbs/organizations/$orgId/employees'
      preLoaderRoute: typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRouteImport
      parentRoute: typeof DemoBreadcrumbsOrganizationsOrgIdRouteRoute
    }
    '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId': {
      id: '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/demo/breadcrumbs/organizations/$orgId/employees/$employeeId'
      preLoaderRoute: typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRouteImport
      parentRoute: typeof DemoBreadcrumbsOrganizationsOrgIdRouteRoute
    }
  }
}

interface DemoBreadcrumbsOrganizationsOrgIdRouteRouteChildren {
  DemoBreadcrumbsOrganizationsOrgIdIndexRoute: typeof DemoBreadcrumbsOrganizationsOrgIdIndexRoute
  DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute: typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute
  DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute: typeof DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute
}

const DemoBreadcrumbsOrganizationsOrgIdRouteRouteChildren: DemoBreadcrumbsOrganizationsOrgIdRouteRouteChildren =
  {
    DemoBreadcrumbsOrganizationsOrgIdIndexRoute:
      DemoBreadcrumbsOrganizationsOrgIdIndexRoute,
    DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute:
      DemoBreadcrumbsOrganizationsOrgIdEmployeesEmployeeIdRoute,
    DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute:
      DemoBreadcrumbsOrganizationsOrgIdEmployeesIndexRoute,
  }

const DemoBreadcrumbsOrganizationsOrgIdRouteRouteWithChildren =
  DemoBreadcrumbsOrganizationsOrgIdRouteRoute._addFileChildren(
    DemoBreadcrumbsOrganizationsOrgIdRouteRouteChildren,
  )

interface DemoBreadcrumbsRouteRouteChildren {
  DemoBreadcrumbsIndexRoute: typeof DemoBreadcrumbsIndexRoute
  DemoBreadcrumbsOrganizationsOrgIdRouteRoute: typeof DemoBreadcrumbsOrganizationsOrgIdRouteRouteWithChildren
  DemoBreadcrumbsOrganizationsIndexRoute: typeof DemoBreadcrumbsOrganizationsIndexRoute
}

const DemoBreadcrumbsRouteRouteChildren: DemoBreadcrumbsRouteRouteChildren = {
  DemoBreadcrumbsIndexRoute: DemoBreadcrumbsIndexRoute,
  DemoBreadcrumbsOrganizationsOrgIdRouteRoute:
    DemoBreadcrumbsOrganizationsOrgIdRouteRouteWithChildren,
  DemoBreadcrumbsOrganizationsIndexRoute:
    DemoBreadcrumbsOrganizationsIndexRoute,
}

const DemoBreadcrumbsRouteRouteWithChildren =
  DemoBreadcrumbsRouteRoute._addFileChildren(DemoBreadcrumbsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoBreadcrumbsRouteRoute: DemoBreadcrumbsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
